apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s3-server-pv
  labels:
    pvname: k8s3-server-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes: # ReadWriteOnce ReadOnlyMany ReadWriteMany 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # Retain Recycle
  storageClassName: nfs # slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /volume2/docker2/k3s-server
    server: 192.168.7.5

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
  name: k8s3-server-pvc-coder
  namespace: default
spec:
  volumeName: k8s3-server-pv
  storageClassName: nfs # slow
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  #selector:
  #  matchLabels:
  #    pvname: k8s3-server-pv

###############################################################
#
#          volumeMounts:
#          - name: volume-pvc
#            subPath: k8s3
#            mountPath: /home/project
#      volumes:
#      - name: volume-pvc
#        persistentVolumeClaim:
#          claimName: k8s3-server-pvc-coder
